version: '3.8'

services:
 
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://user:password@db/library
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
