version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  api:
    build: .
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
